### ISSUE TITLE
PDF Export attempt returns error

### ISSUE THREAD

**Issue by jsmueller7** [recogito/recogito-client#327]
Hi,

I've been testing in my own staging evironment and on the public vico staging server. In both cases every PDF export runs into immediate errors. In my own environment I get an 500, on the public staging server it shows a 502 with this message:

> error decoding lambda response: error decoding lambda response: unexpected end of JSON input

The browser console refers in both cases to `pdf:1`

```
Failed to load resource: the server responded with a status of 500 ()  pdf:1 
```

**Comment by jsmueller7** [comment]
Of course: This accounts for v. 1.2.1

**Comment by rsimon** [comment]
Hi @jsmueller7, I've seen this in other cases where, I believe, it was related to login/session problems. Are you sure this was specifically a problem for PDF exports? (But not access to a project or the annotation view?) Are there any error messages on the Astro server console? (This is where the PDF generation would happen.)

**Comment by jsmueller7** [comment]
Hi @rsimon ,
indeed. The astro server throws a lot of errors. All of them seem to be about `request.headers` beeing not a function.

```
recogito-client TypeError: request.headers.get is not a function
recogito-client     at Object.getAll (file:///app/dist/server/chunks/supabaseServerClient_D2eXh-R2.mjs:9:50)
recogito-client     at getAll (/app/node_modules/@supabase/ssr/dist/main/cookies.js:72:48)
recogito-client     at Object.getItem (/app/node_modules/@supabase/ssr/dist/main/cookies.js:236:42)
recogito-client     at getItemAsync (/app/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:33)
recogito-client     at SupabaseAuthClient._recoverAndRefresh (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1411:69)
recogito-client     at SupabaseAuthClient._initialize (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:196:24)
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:155:35
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:740:36
recogito-client     at SupabaseAuthClient.lockNoOp [as lock] (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:33:18)
recogito-client     at SupabaseAuthClient._acquireLock (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:736:31)
recogito-client 13:02:28 [ERROR] TypeError: request.headers.get is not a function
recogito-client     at Object.getAll (file:///app/dist/server/chunks/supabaseServerClient_D2eXh-R2.mjs:9:50)
recogito-client     at getAll (/app/node_modules/@supabase/ssr/dist/main/cookies.js:72:48)
recogito-client     at Object.getItem (/app/node_modules/@supabase/ssr/dist/main/cookies.js:236:42)
recogito-client     at getItemAsync (/app/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:33)
recogito-client     at SupabaseAuthClient.__loadSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:797:67)
recogito-client     at SupabaseAuthClient._useSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:778:39)
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:706:25
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:724:34
recogito-client 13:02:28 [ERROR] [@astrojs/node] Unhandled rejection while rendering undefined
recogito-client TypeError: request.headers.get is not a function
recogito-client     at Object.getAll (file:///app/dist/server/chunks/supabaseServerClient_D2eXh-R2.mjs:9:50)
recogito-client     at getAll (/app/node_modules/@supabase/ssr/dist/main/cookies.js:72:48)
recogito-client     at Object.getItem (/app/node_modules/@supabase/ssr/dist/main/cookies.js:236:42)
recogito-client     at getItemAsync (/app/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:33)
recogito-client     at SupabaseAuthClient.__loadSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:797:67)
recogito-client     at SupabaseAuthClient._useSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:778:39)
recogito-client     at SupabaseAuthClient._emitInitialSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1213:27)
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1207:22
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:740:36
recogito-client     at SupabaseAuthClient.lockNoOp [as lock] (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:33:18)
recogito-client 13:02:28 [ERROR] [@astrojs/node] Unhandled rejection while rendering https://example.com/de/projects/e34f8436-ebfb-4418-b0c6-47397f8d92f4/export/pdf?document=44996d59-4818-4a6a-9811-692b55016597&private=false
recogito-client TypeError: request.headers.get is not a function
recogito-client     at Object.getAll (file:///app/dist/server/chunks/supabaseServerClient_D2eXh-R2.mjs:9:50)
recogito-client     at getAll (/app/node_modules/@supabase/ssr/dist/main/cookies.js:72:48)
recogito-client     at Object.getItem (/app/node_modules/@supabase/ssr/dist/main/cookies.js:236:42)
recogito-client     at getItemAsync (/app/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:33)
recogito-client     at SupabaseAuthClient.__loadSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:797:67)
recogito-client     at SupabaseAuthClient._useSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:778:39)
recogito-client     at SupabaseAuthClient._emitInitialSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1213:27)
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1207:22
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:740:36
recogito-client     at SupabaseAuthClient.lockNoOp [as lock] (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:33:18)
recogito-client 13:02:28 [ERROR] [@astrojs/node] Unhandled rejection while rendering undefined
recogito-client TypeError: request.headers.get is not a function
recogito-client     at Object.getAll (file:///app/dist/server/chunks/supabaseServerClient_D2eXh-R2.mjs:9:50)
recogito-client     at getAll (/app/node_modules/@supabase/ssr/dist/main/cookies.js:72:48)
recogito-client     at Object.getItem (/app/node_modules/@supabase/ssr/dist/main/cookies.js:236:42)
recogito-client     at getItemAsync (/app/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:33)
recogito-client     at SupabaseAuthClient.__loadSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:797:67)
recogito-client     at SupabaseAuthClient._useSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:778:39)
recogito-client     at SupabaseAuthClient._emitInitialSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1213:27)
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1207:22
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:724:34
recogito-client 13:02:28 [ERROR] [@astrojs/node] Unhandled rejection while rendering https://example.com/de/projects/e34f8436-ebfb-4418-b0c6-47397f8d92f4/export/pdf?document=44996d59-4818-4a6a-9811-692b55016597&private=false
recogito-client TypeError: request.headers.get is not a function
recogito-client     at Object.getAll (file:///app/dist/server/chunks/supabaseServerClient_D2eXh-R2.mjs:9:50)
recogito-client     at getAll (/app/node_modules/@supabase/ssr/dist/main/cookies.js:72:48)
recogito-client     at Object.getItem (/app/node_modules/@supabase/ssr/dist/main/cookies.js:236:42)
recogito-client     at getItemAsync (/app/node_modules/@supabase/auth-js/dist/main/lib/helpers.js:134:33)
recogito-client     at SupabaseAuthClient.__loadSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:797:67)
recogito-client     at SupabaseAuthClient._useSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:778:39)
recogito-client     at SupabaseAuthClient._emitInitialSession (/app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1213:27)
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:1207:22
recogito-client     at /app/node_modules/@supabase/auth-js/dist/main/GoTrueClient.js:724:34
```
